INFO     root:get_log.py:36 执行test_login_failed测试用例
INFO     root:get_log.py:36 登录测试-异常数据
INFO     root:get_log.py:36 准备登录
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:388 POST http://127.0.0.1:64420/session/b47de1dea72016692bced219c4826cfd/element {"using": "id", "value": "txtUsername", "sessionId": "b47de1dea72016692bced219c4826cfd"}
DEBUG    urllib3.connectionpool:connectionpool.py:461 http://127.0.0.1:64420 "POST /session/b47de1dea72016692bced219c4826cfd/element HTTP/1.1" 200 102
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:440 Finished Request
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:388 POST http://127.0.0.1:64420/session/b47de1dea72016692bced219c4826cfd/element/0.9514405059269875-1/value {"text": "\u8d22\u53cb2sna67", "value": ["\u8d22", "\u53cb", "2", "s", "n", "a", "6", "7"], "id": "0.9514405059269875-1", "sessionId": "b47de1dea72016692bced219c4826cfd"}
DEBUG    urllib3.connectionpool:connectionpool.py:461 http://127.0.0.1:64420 "POST /session/b47de1dea72016692bced219c4826cfd/element/0.9514405059269875-1/value HTTP/1.1" 200 72
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:440 Finished Request
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:388 POST http://127.0.0.1:64420/session/b47de1dea72016692bced219c4826cfd/element {"using": "id", "value": "txtPassword", "sessionId": "b47de1dea72016692bced219c4826cfd"}
DEBUG    urllib3.connectionpool:connectionpool.py:461 http://127.0.0.1:64420 "POST /session/b47de1dea72016692bced219c4826cfd/element HTTP/1.1" 200 102
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:440 Finished Request
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:388 POST http://127.0.0.1:64420/session/b47de1dea72016692bced219c4826cfd/element/0.9514405059269875-2/value {"text": "", "value": [], "id": "0.9514405059269875-2", "sessionId": "b47de1dea72016692bced219c4826cfd"}
DEBUG    urllib3.connectionpool:connectionpool.py:461 http://127.0.0.1:64420 "POST /session/b47de1dea72016692bced219c4826cfd/element/0.9514405059269875-2/value HTTP/1.1" 200 72
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:440 Finished Request
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:388 POST http://127.0.0.1:64420/session/b47de1dea72016692bced219c4826cfd/element {"using": "class name", "value": "sso-btn-login", "sessionId": "b47de1dea72016692bced219c4826cfd"}
DEBUG    urllib3.connectionpool:connectionpool.py:461 http://127.0.0.1:64420 "POST /session/b47de1dea72016692bced219c4826cfd/element HTTP/1.1" 200 102
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:440 Finished Request
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:388 POST http://127.0.0.1:64420/session/b47de1dea72016692bced219c4826cfd/element/0.9514405059269875-3/click {"id": "0.9514405059269875-3", "sessionId": "b47de1dea72016692bced219c4826cfd"}
DEBUG    urllib3.connectionpool:connectionpool.py:461 http://127.0.0.1:64420 "POST /session/b47de1dea72016692bced219c4826cfd/element/0.9514405059269875-3/click HTTP/1.1" 200 72
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:440 Finished Request
INFO     root:get_log.py:36 期望值：True
INFO     root:get_log.py:36 出现异常
INFO     root:get_log.py:36 'LoginPage' object has no attribute 'get_account_login_text'
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:388 POST http://127.0.0.1:64420/session/b47de1dea72016692bced219c4826cfd/refresh {"sessionId": "b47de1dea72016692bced219c4826cfd"}
DEBUG    urllib3.connectionpool:connectionpool.py:461 http://127.0.0.1:64420 "POST /session/b47de1dea72016692bced219c4826cfd/refresh HTTP/1.1" 200 72
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:440 Finished Request