{"name": "test_login_failed[data3]", "status": "passed", "attachments": [{"name": "log", "source": "07e946a6-03f5-4b6f-a4c6-d1724d5db888-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'name': '登录功能-异常登录-密码错误', 'username': '财友2sna6763', 'password': '654321'}"}], "start": 1609589976662, "stop": 1609589977388, "uuid": "8df51405-00ad-4a54-91ea-a496c84275b2", "historyId": "dbeb2a97f887c27b8015e9253b5aa614", "testCaseId": "130e6dce60bc4ef9d882c5f0465dc1d6", "fullName": "cases.test_login.TestLogin#test_login_failed", "labels": [{"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "PC-20200718ELAI"}, {"name": "thread", "value": "3340-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.test_login"}]}