{"name": "test_login_failed[data3]", "status": "passed", "attachments": [{"name": "log", "source": "c2519d8e-a72a-4b4f-b97c-faaec3f604d8-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'name': '登录功能-异常登录-密码错误', 'username': '财友2sna6763', 'password': '654321'}"}], "start": 1609589880234, "stop": 1609589880969, "uuid": "19a2590e-c16e-4049-8aef-233a632fdad0", "historyId": "dbeb2a97f887c27b8015e9253b5aa614", "testCaseId": "130e6dce60bc4ef9d882c5f0465dc1d6", "fullName": "cases.test_login.TestLogin#test_login_failed", "labels": [{"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "PC-20200718ELAI"}, {"name": "thread", "value": "13008-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.test_login"}]}