{"name": "test_login_failed[data1]", "status": "passed", "parameters": [{"name": "data", "value": "{'name': '登录功能-正常登录-用户名错误', 'username': '财友qfy46', 'password': 'xxx123456'}"}], "start": 1609585441052, "stop": 1609585442070, "uuid": "62005aea-0dd5-430d-bde2-2ffe2c7b3041", "historyId": "28fbee3f7849e5c692210a9f12e7fe96", "testCaseId": "130e6dce60bc4ef9d882c5f0465dc1d6", "fullName": "cases.test_login.TestLogin#test_login_failed", "labels": [{"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "PC-20200718ELAI"}, {"name": "thread", "value": "5488-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.test_login"}]}