{"uuid": "c76aae18-1947-4044-9860-624ed1544c69", "children": ["cc6418e1-a403-4732-aab4-c03fbc3b1aab"], "befores": [{"name": "handler", "status": "broken", "statusDetails": {"message": "TypeError: 'module' object is not callable\n", "trace": "  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\po_jrj\\cases\\conftest.py\", line 9, in handler\n    driver = webdriver.chrome()  #调取chrom浏览器\n"}, "start": 1609333934271, "stop": 1609333934271}], "start": 1609333934271, "stop": 1609333934368}