{"name": "test_login_failed[data1]", "status": "passed", "attachments": [{"name": "log", "source": "b6e26a21-3d17-48c5-930b-2a035438ba3f-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'name': '登录功能-异常登录-用户名错误', 'username': 'abc', 'password': '654321Ok'}"}], "start": 1609595070318, "stop": 1609595071574, "uuid": "1e8f5ebc-3d48-40af-bbe3-d8d8b3a7f2ae", "historyId": "28fbee3f7849e5c692210a9f12e7fe96", "testCaseId": "130e6dce60bc4ef9d882c5f0465dc1d6", "fullName": "cases.test_login.TestLogin#test_login_failed", "labels": [{"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "PC-20200718ELAI"}, {"name": "thread", "value": "12384-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.test_login"}]}