{"name": "test_login_failed[data3]", "status": "passed", "attachments": [{"name": "log", "source": "e6d311b4-f8e9-4d6c-910b-186b8d41bb3d-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'name': '登录功能-异常登录-密码错误', 'username': '财友2sna6763', 'password': '654321'}"}], "start": 1609594973785, "stop": 1609594974636, "uuid": "d7a4cd2c-c40e-4211-a367-86f3e58eda6a", "historyId": "dbeb2a97f887c27b8015e9253b5aa614", "testCaseId": "130e6dce60bc4ef9d882c5f0465dc1d6", "fullName": "cases.test_login.TestLogin#test_login_failed", "labels": [{"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "PC-20200718ELAI"}, {"name": "thread", "value": "1104-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.test_login"}]}